# image: kradalby/python
image: kradalby/ci-tox
git:
  path: github.com/kradalby/mailpimp

env:

script:
    - pip install tox
    - tox

notify:
  email:
    recipients:
      - kradalby@kradalby.no
