derp@example.com:sender@example.com:receiver@example.com
derp1@example.com:sender@example.com sender1@example.com sender2@example.com sender3@example.com:receiver@example.com
derp2@example.com:sender@example.com:receiver@example.com receiver1@example.com receiver2@example.com receiver3@example.com
derp3@example.com:sender@example.com sender1@example.com sender2@example.com sender3@example.com:receiver@example.com receiver1@example.com receiver2@example.com receiver3@example.com
